# Auto Start tmux. This needs to be placed above Powerlevel10k instant prompt.
if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [[ -z "$TMUX" ]]; then
  if [[ -n "$PS1" ]] && [[ -z "$TMUX" ]] && [[ -n "$SSH_CONNECTION" ]]; then
    tmux attach-session -t ssh_tmux || tmux new-session -s ssh_tmux
  fi
  if [[ -n "$PS1" ]] && [[ -z "$TMUX" ]]; then
    tmux attach-session -t default || tmux new-session -s default
  fi
fi

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="ys"

plugins=(git vi-mode vscode tmux zsh-autosuggestions zsh-syntax-highlighting)

# Source various files.
source $ZSH/oh-my-zsh.sh

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Alias
alias python=python3
alias py=python
alias pip=pip3

# Environment variables
export SHELL=$(which zsh)
export EDITOR=vim
export PYENV_ROOT="$HOME/.pyenv"

# PATHs
export PATH="$PYENV_ROOT/bin:$PATH"

# Post Processing
command -v pyenv &> /dev/null && eval "$(pyenv init -)"
eval "$(pyenv init -)"